---
- hosts: master
  vars_files:
  - env_variables 
  tasks:
  - name: Restarting service
    service:
     name: "{{ item }}"
     state: restarted
     enabled: yes
    with_items: "{{ services }}"
    become: yes

  - name: Resetting K8s kubeadm
    become: yes
    command:
      cmd: kubeadm reset
      stdin: "y"

  - name: Pulling images required for setting up a Kubernetes cluster
    become: yes
    shell: kubeadm config images pull

  - name: Initializing Kubernetes cluster
    become: yes
    shell: kubeadm init --apiserver-advertise-address {{ad_addr}} --pod-network-cidr={{cidr_v}}

  - name: Fetching the token
    become: yes
    shell: kubeadm token create --print-join-command
    register: token

  - name: Storing Generated token for future purpose.
    become: yes
    local_action: copy content={{ token.stdout }} dest={{ token_file }}

  - name: Copying required files
    become: yes
    shell: |
     mkdir -p $HOME/.kube
     cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
     chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Install Network Add-on
    become: yes
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

  - name: Download admin.conf file
    become: yes
    fetch: 
      src: ~/.kube/config
      dest: ./
